force-app/main/default/objects/Feature_Flag__c/Feature_Flag__c.object-meta.xml
<CustomObject>
    <label>Feature Flag</label>
    <nameField>
        <label>Feature Flag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Flags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feature_Flag__c/fields/Last_Used__c.field-meta.xml
<CustomField>
    <fullName>Last_Used__c</fullName>
    <label>Last Used</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/FeatureFlagControllerTest.cls
@IsTest
public with sharing class FeatureFlagControllerTest {
    private static User getRunAsUser() {
        return [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    }

    @IsTest
    static void getStatsTest(){
        User runAsUser = getRunAsUser();
        System.runAs(runAsUser) {
            Feature_Flag__c flag = FeatureToggleTest.createFlag('Test', true);
            DateTime lastUsed = DateTime.now().addHours(-1);
            flag.Last_Used__c = lastUsed;
            update flag;

            Test.startTest();
            FeatureFlagController.StatWrapper stats = FeatureFlagController.getFeatureStats(flag.Id);
            Test.stopTest();

            System.assertEquals(lastUsed, stats.lastUsed, 'Expected lastUsed to match the record.');
        }
    }
}