force-app/main/default/objects/Feature_Flag__c/Feature_Flag__c.object-meta.xml
<CustomObject>
    <label>Feature Flag</label>
    <nameField>
        <label>Feature Flag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Flags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feature_Flag__c/fields/ActivationDateTime__c.field-meta.xml
<CustomField>
    <fullName>ActivationDateTime__c</fullName>
    <description>The date and time that the feature will activate upon.</description>
    <inlineHelpText>The date and time that the feature will activate upon.</inlineHelpText>
    <label>Activation Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Feature_Flag__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this checkbox is checked the feature will be active.</description>
    <inlineHelpText>When this checkbox is checked the feature will be active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Feature_Flag__c/fields/DeactivationDateTime__c.field-meta.xml
<CustomField>
    <fullName>DeactivationDateTime__c</fullName>
    <description>The date and time that the feature will deactivate upon.</description>
    <inlineHelpText>The date and time that the feature will deactivate upon.</inlineHelpText>
    <label>Deactivation Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Feature_Flag__c/fields/Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Expire_Date__c</fullName>
    <inlineHelpText>The date and time that the feature will expire. This will NOT disable the
        feature. It will cause tests to fail after this date.</inlineHelpText>
    <label>Test Failure Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flag_Override__c/Flag_Override__c.object-meta.xml
<CustomObject>
    <label>Flag Override</label>
    <nameField>
        <displayFormat>FR{0000}</displayFormat>
        <label>Flag Override</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flag Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flag_Override__c/fields/Feature_Flag__c.field-meta.xml
<CustomField>
    <fullName>Feature_Flag__c</fullName>
    <label>Feature Flag</label>
    <referenceTo>Feature_Flag__c</referenceTo>
    <relationshipLabel>Flag Overrides</relationshipLabel>
    <relationshipName>Flag_Overrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Flag_Override__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Flag_Override__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Flag_Overrides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FeatureFlag.cls
global without sharing class FeatureFlag {
    private static Map<String, FeatureFlag> features = new Map<String, FeatureFlag>();

    @TestVisible private Feature_Flag__c record;

    private FeatureFlag(Feature_Flag__c record) {
        this.record = record;
    }

    private FeatureFlag() {

    }

    global static FeatureFlag getFeatureFlag(String name) {
        if(features.containsKey(name) == false) {
            List<Feature_Flag__c> featureToggleRecord = [SELECT Id, Name, Active__c, activationDateTime__c, Expire_Date__c, deactivationDateTime__c,
                                                         (SELECT Id, User__c, IsActive__c FROM Flag_Overrides__r WHERE User__c = : UserInfo.getUserId())
                                                         FROM Feature_Flag__c
                                                         WHERE Name = : name
                                                                      LIMIT 1];
            if(featureToggleRecord.size() == 1) {
                features.put(name, new FeatureFlag(featureToggleRecord[0]));
            } else {
                features.put(name, new FeatureFlag(new Feature_Flag__c(Active__c = Test.isRunningTest())));
            }
        }
        return features.get(name);
    }

    @AuraEnabled(cacheable = true)
    global static Boolean Active(String name){
        return getFeatureFlag(name).IsActive;
    }

    /**
     * @description Determines if the record is not null and that the Active__c
     *              field is set to true.
     */
    global Boolean IsActive {
        get {
            // Return early if the record is null.
            if (this.record == null) {return false;}

            if (this.isOverriden) {
                return this.record.Flag_Overrides__r[0].IsActive__c;
            }

            // Determine whether the activation and deactivation time frames have been met.

            if(this.record.Active__c == false && activationDateTime != null && DateTime.now() >= activationDateTime) {
                this.record.Active__c = true;
                // update this.record;
            }
            if(this.record.Active__c == true && deactivationDateTime != null && DateTime.now() >= deactivationDateTime) {
                this.record.Active__c = false;
                // update this.record;
            }

            return this.record.Active__c == true;
        }
    }

    /**
     * @description The activationDateTime__c of the stored Feature_Flag__c record.
     */
    @TestVisible
    private Datetime activationDateTime {
        get {
            if (this.record != null) {
                return this.record.activationDateTime__c;
            }
            return null;
        }
    }

    /**
     * @description The activationDateTime__c of the stored Feature_Flag__c record.
     */
    @TestVisible
    private Datetime deactivationDateTime {
        get {
            if (this.record != null) {
                return this.record.deactivationDateTime__c;
            }
            return null;
        }
    }

    /**
     * @description The activationDateTime__c of the stored Feature_Flag__c record.
     */
    @TestVisible
    private Datetime expireDateTime {
        get {
            if (this.record != null) {return this.record.Expire_Date__c;}
            return null;
        }
    }

    @TestVisible
    private Boolean isOverriden {
        get {
            return this.record.Flag_Overrides__r.isEmpty() == false;
        }
    }

    @TestVisible
    static FeatureFlag createEmptyForTest() {
        return new FeatureFlag();
    }

    public class ExpiredFlagException extends Exception {

    }

    public class UndefinedFlagException extends Exception {

    }
}