force-app/main/default/objects/Feature_Flag__c/Feature_Flag__c.object-meta.xml
<CustomObject>
    <label>Feature Flag</label>
    <nameField>
        <label>Feature Flag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Flags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feature_Flag__c/fields/Last_Used__c.field-meta.xml
<CustomField>
    <fullName>Last_Used__c</fullName>
    <label>Last Used</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/FeatureFlagController.cls
public with sharing class FeatureFlagController {
    @AuraEnabled(cacheable = true)
    public static StatWrapper getFeatureStats(Id recordId){
        Feature_Flag__c flag = [SELECT Id, Last_Used__c
                                FROM Feature_Flag__c
                                WHERE Id = : recordId
        ];

        StatWrapper stats = new StatWrapper();
        stats.lastUsed = flag.Last_Used__c;
        return stats;
    }

    public class StatWrapper {
        @AuraEnabled
        public DateTime lastUsed;
    }
}